spring.application.name=demo-jdbc-jpa

# Config for JDBC
spring.datasource.url=jdbc:h2:mem:orderdb;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.sql.init.mode=always

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

logging.level.org.springframework.jdbc.core=DEBUG

